[project]
name = "obd2-link"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "awsiotsdk>=1.26.0",
    "google-cloud-bigquery>=3.41.0",
    "obd>=0.7.3",
    "pynmea2>=1.19.0",
    "python-dotenv>=1.2.2",
    "pyserial>=3.5",
]
